# Generated by Django 5.0.2 on 2024-02-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
